package com.example.data.service

import com.example.BuildConfig
import com.example.data.model.LocationInfo
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

class GeminiExplanationService {
    private val client = OkHttpClient.Builder()
        .connectTimeout(6, TimeUnit.SECONDS)
        .readTimeout(8, TimeUnit.SECONDS)
        .build()

    private val apiKey: String by lazy {
        try {
            val field = BuildConfig::class.java.getField("GEMINI_API_KEY")
            val value = field.get(null) as? String ?: ""
            if (value.isBlank() || value.contains("MY_GEMINI_API_KEY")) "" else value
        } catch (e: Exception) {
            ""
        }
    }

    val isConfigured: Boolean
        get() = apiKey.isNotBlank()

    /**
     * Generates an explanation for "Why is this location at risk?" and "Recommended authority actions"
     */
    suspend fun getRiskExplanation(
        location: LocationInfo,
        rainfallMmHr: Double,
        drainageStressPercent: Int
    ): Pair<String, String> = withContext(Dispatchers.IO) {
        if (!isConfigured) {
            return@withContext getDeterministicExplanation(location, rainfallMmHr, drainageStressPercent)
        }

        try {
            val prompt = """
                Location: ${location.name} (${location.ward}, Bengaluru)
                Elevation: ${location.elevationMeters}m (Basin depression)
                Current Rainfall: $rainfallMmHr mm/hr
                Drainage Hydraulic Stress: $drainageStressPercent%
                Current Flood Risk: ${location.currentRisk}% (${location.riskLevel.name})
                
                Provide:
                1. A 2-sentence physical explanation of why this location is at risk (mentioning rainfall and drainage coupling).
                2. Three prioritized government agency action recommendations.
                Keep the tone professional, objective, and emergency-ready.
            """.trimIndent()

            val requestJson = JSONObject().apply {
                val contentsArray = JSONArray().apply {
                    val contentObj = JSONObject().apply {
                        val partsArray = JSONArray().apply {
                            val partObj = JSONObject().apply {
                                put("text", prompt)
                            }
                            put(partObj)
                        }
                        put("parts", partsArray)
                    }
                    put(contentObj)
                }
                put("contents", contentsArray)
            }

            val requestBody = requestJson.toString().toRequestBody("application/json".toMediaType())
            val url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=$apiKey"
            val request = Request.Builder().url(url).post(requestBody).build()
            val response = client.newCall(request).execute()

            if (response.isSuccessful) {
                val responseBody = response.body?.string() ?: ""
                val resObj = JSONObject(responseBody)
                val text = resObj.getJSONArray("candidates")
                    .getJSONObject(0)
                    .getJSONObject("content")
                    .getJSONArray("parts")
                    .getJSONObject(0)
                    .getString("text")

                Pair(text, "Generated by Gemini 2.5 Flash")
            } else {
                getDeterministicExplanation(location, rainfallMmHr, drainageStressPercent)
            }
        } catch (e: Exception) {
            getDeterministicExplanation(location, rainfallMmHr, drainageStressPercent)
        }
    }

    private fun getDeterministicExplanation(
        location: LocationInfo,
        rainfallMmHr: Double,
        drainageStressPercent: Int
    ): Pair<String, String> {
        val why = "${location.name} is in an urban drainage depression (${location.elevationMeters}m ASL). " +
                "Precipitation of ${rainfallMmHr.toInt()} mm/hr exceeds the local infiltration threshold, " +
                "causing rapid surface runoff that surcharges the primary Rajakaluve drain to $drainageStressPercent% capacity. " +
                "Backwater effects from downstream culverts create localized inundation risks."

        val action = "1. BBMP Stormwater: Inspect ${location.name} culvert grates and deploy high-capacity mobile dewatering pumps.\n" +
                "2. Bengaluru Traffic Police: Prepare detour signs and monitor water accumulation depth on Outer Ring Road.\n" +
                "3. Disaster Management: Pre-position quick response teams at nearby high ground."

        return Pair("$why\n\n$action", "Deterministic baseline explanation (Gemini API key not configured)")
    }
}
